import { AppConfigModule, AppConfigService } from '@app/config';
import { Global, Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import {
  Anaglyph,
  AssetNote,
  AttachedMedia,
  Category,
  Device,
  DeviceToken,
  ErrorCode,
  ErrorCodeLinking,
  ErrorCodeMachineType,
  Group,
  Job,
  Model,
  Note,
  Notification,
  Organization,
  OTP,
  Part,
  Permission,
  Procedure,
  Repetition,
  Role,
  SafetyMeasure,
  SafetyMeasureUser,
  Section,
  Sketch,
  Status,
  TaskType,
  Troubleshoot,
  TroubleshootStep,
  User,
  UserGroup,
  UserRole,
  WorkOrderTodo,
  WorkOrder,
  Step,
  WrittenIssue,
  DeskProcedure,
  TabletVersions,
  RolePermissions,
  SlaveMachine,
  RealiseNoteEntity,
  Database,
  PartNotes,
  PartFields,
} from './model';
import { CustomUniqueValidator } from './validator';
import { ModelSubscriber } from './subscriber';
import { Media } from './model/media.entity';
import {
  CommonStepService,
  CustomUniqueService,
  FilterService,
} from './service';
import { ActiveStorageAttachment } from './model/active-storage-attachments.entity';
import { ActiveStorageBlob } from './model/active-storage-blobs.entity';

export const DBSchemas = {
  model: TypeOrmModule.forFeature([Model]),
  category: TypeOrmModule.forFeature([Category]),
  organization: TypeOrmModule.forFeature([Organization]),
  device: TypeOrmModule.forFeature([Device]),
  workOrder: TypeOrmModule.forFeature([WorkOrder]),
  procedure: TypeOrmModule.forFeature([Procedure]),
  step: TypeOrmModule.forFeature([Step]),
  anaglyph: TypeOrmModule.forFeature([Anaglyph]),
  section: TypeOrmModule.forFeature([Section]),
  writtenIssue: TypeOrmModule.forFeature([WrittenIssue]),
  sketch: TypeOrmModule.forFeature([Sketch]),
  assetNote: TypeOrmModule.forFeature([AssetNote]),
  errorCodeLinking: TypeOrmModule.forFeature([ErrorCodeLinking]),
  troubleshootStep: TypeOrmModule.forFeature([TroubleshootStep]),
  troubleshoot: TypeOrmModule.forFeature([Troubleshoot]),
  workOrderTodo: TypeOrmModule.forFeature([WorkOrderTodo]),
  safetyMeasure: TypeOrmModule.forFeature([SafetyMeasure]),
  safetyMeasureUser: TypeOrmModule.forFeature([SafetyMeasureUser]),
  attachedMedia: TypeOrmModule.forFeature([AttachedMedia]),
  status: TypeOrmModule.forFeature([Status]),
  errorCode: TypeOrmModule.forFeature([ErrorCode]),
  errorCodeMachineType: TypeOrmModule.forFeature([ErrorCodeMachineType]),
  media: TypeOrmModule.forFeature([Media]),
  part: TypeOrmModule.forFeature([Part]),
  note: TypeOrmModule.forFeature([Note]),
  user: TypeOrmModule.forFeature([User]),
  taskType: TypeOrmModule.forFeature([TaskType]),
  deviceToken: TypeOrmModule.forFeature([DeviceToken]),
  group: TypeOrmModule.forFeature([Group]),
  notification: TypeOrmModule.forFeature([Notification]),
  otp: TypeOrmModule.forFeature([OTP]),
  role: TypeOrmModule.forFeature([Role]),
  userGroup: TypeOrmModule.forFeature([UserGroup]),
  userRole: TypeOrmModule.forFeature([UserRole]),
  job: TypeOrmModule.forFeature([Job]),
  repetition: TypeOrmModule.forFeature([Repetition]),
  permission: TypeOrmModule.forFeature([Permission]),
  activeStorageAttachment: TypeOrmModule.forFeature([ActiveStorageAttachment]),
  activeStorageBlob: TypeOrmModule.forFeature([ActiveStorageBlob]),
  tabletVersions: TypeOrmModule.forFeature([TabletVersions]),
  rolePermissions: TypeOrmModule.forFeature([RolePermissions]),
  slaveMachine: TypeOrmModule.forFeature([SlaveMachine]),
  realiseNote: TypeOrmModule.forFeature([RealiseNoteEntity]),
  database: TypeOrmModule.forFeature([Database]),
  partNotes: TypeOrmModule.forFeature([PartNotes]),
  partFields: TypeOrmModule.forFeature([PartFields]),
};

@Global()
@Module({
  imports: [
    AppConfigModule,
    DBSchemas.role,
    DBSchemas.section,
    DBSchemas.model,
    DBSchemas.taskType,
    DBSchemas.user,
    DBSchemas.permission,
    TypeOrmModule.forRootAsync({
      inject: [AppConfigService],
      useFactory: async (configService: AppConfigService) => ({
        ...configService.getTypeOrmConfig(),
        subscribers: [ModelSubscriber],
        entities: [
          Organization,
          Category,
          Model,
          WorkOrder,
          Device,
          Procedure,
          Step,
          Anaglyph,
          Section,
          WrittenIssue,
          Sketch,
          AssetNote,
          ErrorCodeLinking,
          TroubleshootStep,
          Troubleshoot,
          WorkOrder,
          WorkOrderTodo,
          SafetyMeasure,
          SafetyMeasureUser,
          AttachedMedia,
          Status,
          ErrorCode,
          ErrorCodeMachineType,
          Media,
          Part,
          Note,
          User,
          TaskType,
          DeviceToken,
          Group,
          Notification,
          OTP,
          Role,
          UserGroup,
          UserRole,
          Job,
          Repetition,
          Permission,
          ActiveStorageAttachment,
          ActiveStorageBlob,
          DeskProcedure,
          TabletVersions,
          RolePermissions,
          SlaveMachine,
          RealiseNoteEntity,
          Database,
          PartNotes,
          PartFields,
        ],
      }),
    }),
  ],
  providers: [
    CustomUniqueValidator,
    FilterService,
    CustomUniqueService,
    CommonStepService,
  ],
  exports: [
    CustomUniqueValidator,
    FilterService,
    CustomUniqueService,
    CommonStepService,
  ],
})
export class SchemaModule {}
